from enum import StrEnum


class Measurement(StrEnum):
    CPU_CAPACITY = "CPU.Capacity"
    CPU_ALLOCATED = "CPU.Allocated"
    CPU_AVAILABLE = "CPU.Available"
    CPU_USAGE = "CPU.Usage"
    GPU_ALLOCATED = "GPU.Allocated"
    GPU_CAPACITY = "GPU.Capacity"
    GPU_AVAILABLE = "GPU.Available"
    GPU_USAGE = "GPU.Usage"
    RAM_CAPACITY = "RAM.Capacity"
    RAM_ALLOCATED = "RAM.Allocated"
    RAM_AVAILABLE = "RAM.Available"
    RAM_USAGE = "RAM.Usage"
    STORAGE_CAPACITY = "Storage.Capacity"
    STORAGE_ALLOCATED = "Storage.Allocated"
    STORAGE_AVAILABLE = "Storage.Available"
    STORAGE_USAGE = "Storage.Usage"
    NETWORK_CAPACITY = "Network.Capacity"
    NETWORK_ALLOCATED = "Network.Allocated"
    NETWORK_AVAILABLE = "Network.Available"
    NETWORK_USAGE = "Network.Usage"
    ENERGY_INDEX = "Energy.Index"
    ENERGY_ALLOCATED = "Energy.Allocated"
    ENERGY_CAPACITY = "Energy.Capacity"
    ENERGY_AVAILABLE = "Energy.Available"
    ENERGY_USAGE = "Energy.Usage"
