replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: {}

service:
  type: ClusterIP
  port: 8080

settings:
  builder:
    builder_tick_seconds: 60
    node_port: 80
    single_slice_url: http://metadata-service:80
    is_single_slice: False
    queries:
      node_queries: []
      pod_queries: []
      workload_queries: []
  influxdb:
    org: org
    timeout: 60000
    token: token
    url: test
  k8s:
    in_cluster: true
  metadata:
    metadata_service_push_period_sec: 60
    metadata_service_url: metadata-service
  prometheus:
    endpoint_port: 8080
  prometheus_client:
    url: prometheus.integration
