apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: kg-exporter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kg-exporter
  template:
    metadata:
      labels:
        app: kg-exporter
    spec:
      containers:
      - name: kg-exporter
        image: kg_exporter:latest
        ports:
        - containerPort: 8080