builder:
  builder_tick_seconds: 10
  node_port: 80
  queries:
    node_queries: []
    pod_queries: []
    workload_queries: []
influxdb:
  org: org
  timeout: 60000
  token: token
  url: test
k8s:
  in_cluster: false
metadata:
  metadata_service_push_period_sec: 60
  metadata_service_url: metadata.integration
  # metadata_service_url: metadata-service
  use_single_url: true
prometheus:
  endpoint_port: 8080
prometheus_client:
  url: prometheus.integration
