kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app.fullname" . }}-role
rules:
- apiGroups: ["apps", "batch"]
  resources: ["deployments", "jobs", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["list", "watch", "get"]
- apiGroups: [""]
  resources: ["configmaps", "deployments", "statefulsets", "jobs", "nodes", "daemonsets", "replicasets", "pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["watch"]
