kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app.fullname" . }}-binding
subjects:
- kind: ServiceAccount
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "app.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
