kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app.fullname" . }}-role
rules:
- apiGroups: ["apps", "batch"]
  resources: ["deployments", "statefulsets", "jobs"]
  verbs: ["list", "watch"]
