- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: coredns
    uid: 1
    namespace: kube-system
    ownerReferences:
    - apiVersion: minio.min.io/v2
      kind: CRD
      name: crd-resource
    labels:
      k8s-app: kube-dns
  spec:
    replicas: 2
    selector:
      matchLabels:
        k8s-app: kube-dns
    template:
      metadata:
        labels:
          k8s-app: kube-dns
        annotations:
          glaciation-project.eu/energy-capacity: '100'
          glaciation-project.eu/network-capacity: '1010'
          glaciation-project.eu/energy-allocated: '100'
          glaciation-project.eu/network-allocated: '1010'
      spec:
        initContainers:
        - name: init-coredns
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
        containers:
        - name: coredns
          resources:
            limits:
              memory: 170Mi
              nvidia.com/gpu: 101
            requests:
              cpu: 100m
              memory: 70Mi
              nvidia.com/gpu: 101
        - name: coredns-other
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
              ephemeral-storage: 100500
        schedulerName: default-scheduler
