name: Build web

on:
  workflow_call:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: glaciation-heu/kg_exporter

jobs:
  build_web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install poetry
      run: pip install poetry

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Make versions
      run: |
        chmod +x ./tools/version.sh
        ./tools/version.sh "${{ github.sha }}" "${{ secrets.DOCKER_IMAGE_NAME }}"
        echo "APP_VERSION=$(cat "./VERSION")" >> $GITHUB_ENV
        echo "DOCKER_IMAGES=$(cat "./DOCKER_IMAGES")" >> $GITHUB_ENV

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        # tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.DOCKER_IMAGES }}

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-root --with dev

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Create a github release
      run: gh release create "${{ env.APP_VERSION }}"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Publish Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ github.token }}
        target_dir: "./helm-charts/"
